<?php

/**
 * Generates real dev-only values for .env.supabase, based on the structure
 * documented in .env.supabase.example. Coolify's magic-var engine
 * (SERVICE_<TYPE>_<NAME> -> auto-generated password/user/FQDN/URL) only runs
 * inside Coolify at deploy time, so plain `docker compose` needs this done
 * up front for local dev.
 *
 * Not a general-purpose Coolify magic-var emulator — only implements the
 * subset this project's docker-compose.yml actually needs.
 */
function randomPassword(int $length = 40): string
{
    return substr(strtr(base64_encode(random_bytes($length)), '+/', '-_'), 0, $length);
}

function randomUser(int $length = 16): string
{
    return substr(bin2hex(random_bytes($length)), 0, $length);
}

function base64UrlEncode(string $data): string
{
    return rtrim(strtr(base64_encode($data), '+/', '-_'), '=');
}

function signSupabaseJwt(string $role, string $secret): string
{
    $header = base64UrlEncode(json_encode(['alg' => 'HS256', 'typ' => 'JWT']));
    $now = time();
    $payload = base64UrlEncode(json_encode([
        'role' => $role,
        'iss' => 'supabase-dev-local',
        'iat' => $now,
        // 10 years — this is a local dev key, not a production secret.
        'exp' => $now + (10 * 365 * 24 * 60 * 60),
    ]));
    $signature = base64UrlEncode(hash_hmac('sha256', "$header.$payload", $secret, true));

    return "$header.$payload.$signature";
}

$jwtSecret = randomPassword(48);
$kongPort = getenv('DEV_KONG_PORT') ?: '8000';

$generated = [
    'SERVICE_FQDN_SUPABASEKONG' => 'localhost',
    'SERVICE_URL_SUPABASEKONG' => "http://localhost:$kongPort",
    'SERVICE_FQDN_SUPABASEKONG_8000' => 'localhost',
    'SERVICE_URL_SUPABASEKONG_8000' => "http://localhost:$kongPort",
    'SERVICE_USER_ADMIN' => randomUser(),
    'SERVICE_PASSWORD_ADMIN' => randomPassword(24),
    'SERVICE_PASSWORD_JWT' => $jwtSecret,
    'SERVICE_PASSWORD_POSTGRES' => randomPassword(32),
    'SERVICE_PASSWORD_PGMETACRYPTO' => bin2hex(random_bytes(32)),
    'SERVICE_PASSWORD_LOGFLARE' => randomPassword(32),
    'SERVICE_PASSWORD_LOGFLAREPRIVATE' => randomPassword(32),
    'SERVICE_USER_MINIO' => randomUser(),
    'SERVICE_PASSWORD_MINIO' => randomPassword(24),
    // Phoenix/Elixir secret_key_base values — long random strings.
    'SERVICE_PASSWORD_SUPAVISORSECRET' => randomPassword(64),
    // Supavisor's Cloak vault key. If supavisor fails to boot complaining
    // about VAULT_ENC_KEY length, see the self-hosting docs for the exact
    // expected size — this generates a generous 32-byte value as a default.
    'SERVICE_PASSWORD_VAULTENC' => base64_encode(random_bytes(32)),
    'SERVICE_SUPABASEANON_KEY' => signSupabaseJwt('anon', $jwtSecret),
    'SERVICE_SUPABASESERVICE_KEY' => signSupabaseJwt('service_role', $jwtSecret),
    // Same likely-bug as documented in .ai/rules: SECRET_PASSWORD_REALTIME
    // does not match Coolify's magic-var pattern, so it needs a real value
    // here too.
    'SECRET_PASSWORD_REALTIME' => randomPassword(64),
];

$examplePath = __DIR__.'/../.env.supabase.example';
$lines = file($examplePath, FILE_IGNORE_NEW_LINES);

$output = [];
$output[] = '# Generated by volumes/generate-dev-env.php for local dev — DO NOT COMMIT.';
$output[] = '# Regenerate by deleting .env.supabase and re-running volumes/generate-dev-env.sh.';
$output[] = '';

foreach ($lines as $line) {
    if (preg_match('/^([A-Z0-9_]+)=/', $line, $m) && array_key_exists($m[1], $generated)) {
        $output[] = $m[1].'='.$generated[$m[1]];

        continue;
    }
    $output[] = $line;
}

// SERVICE_ROLE_KEY_ASYMMETRIC / ANON_KEY_ASYMMETRIC are intentionally left
// blank (see .env.supabase.example) — the asymmetric (ES256) JWT scheme is
// optional and off unless set.

echo implode("\n", $output)."\n";
